GCC/Controllers/CampanhaController.cs
using GCC.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using GCC.Managers;
using GCC.Class;

using GCC.CatalogoProduto;
using System.Collections.Generic;

namespace GCC.Controllers
{
    public class CampanhaController : Controller
    {
        // GET: Campanha
        string con = ConnectionDB.GetDBConnectionString;
        public ActionResult Index()
        {
            return View();
        }

        // GET: Campanha/Details/5
      
        public ActionResult Details(int id)
        {
            Campanha campanha = new Campanha();
            using (GCCEntities db = new GCCEntities(con))
            {
                try
                {
                    List<Product> lista = new List<Product>();
                   
                    Session["lista"] = null;
                    Session["ListaProduto"] = null;
                    //@Session["PaginaCampanha"] = pagina;
                     campanha = Campanha_Manager.GetCampanha(ID:id,con:con);
                    var listaProvincia = db.tblProvincia.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                    //listaProvincia.Add(new tblProvincia { ID = 0, Provincia = "Todas", Estado = true });
                    ViewBag.listaProvincia = listaProvincia;

                    var listaPrioridade = db.tblPrioridade.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                    ViewBag.listaPrioridade = listaPrioridade;

                    var listaRede = db.tblRede.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                    //listaRede.Add(new tblRede { ID = 0, Rede = "Todas", Estado = true });
                    ViewBag.listaRede = listaRede;

                    var listaRecorrencia = db.tblRecorrencia.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                    ViewBag.listaRecorrencia = listaRecorrencia;

                    var listaCanal = db.tblCanal.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                    ViewBag.listaCanal = listaCanal;

                    var listaRazaoContacto = db.tblRazaoContacto.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                    ViewBag.listaRazaoContacto = listaRazaoContacto;

                    lista = Campanha_Manager.GetProductRootList();
                    Session["ListaProduto"] = lista;
                    Session["CampanhaID"] = campanha.CampanhaID;
                    var listaProduto = lista.Where(a => a.ProductLevel == 0).ToList();
                    ViewBag.listaProduto = listaProduto;
                    //string.Join(",", yourListVariableHere);
                    ViewBag.provincias = string.Join(",",campanha.provincia.Select(a => a.ProvinciaID).ToList());
                    ViewBag.redes = string.Join(",", campanha.rede.Select(a => a.RedeID).ToList());
                    ViewBag.semanas = getSemanaList();



                }

                catch (Exception erro)
                {
                    LogInicializer.logger.Info(DateTime.Now + " -CampanhaController - Details)- ", erro);
                    throw erro;
                }

            }
            return View("Manutencao",campanha);
            //return PartialView("Details",campanha);
        }
        public List<Semana> getSemanaList()
        {
            List<Semana> lista = new List<Semana>();
            lista.Add(new Semana { Value=1,Text="Domingo"});
            lista.Add(new Semana { Value = 2, Text = "Segunda" });
            lista.Add(new Semana { Value = 3, Text = "Terça" });
            lista.Add(new Semana { Value = 4, Text = "Quarta" });
            lista.Add(new Semana { Value = 5, Text = "Quinta" });
            lista.Add(new Semana { Value = 6, Text = "Sexta" });
            lista.Add(new Semana { Value = 7, Text = "Sábado" });

            return lista;
        }
        // GET: Campanha/Create
        public ActionResult Create()
        {
            using (GCCEntities db = new GCCEntities(con))
            {
                try
                {
                    List<Product> lista = new List<Product>();
                    Session["lista"] = null;
                    Session["ListaProduto"] = null;
                    
                    var listaProvincia = db.tblProvincia.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                   
                    ViewBag.listaProvincia = listaProvincia;

                    var listaPrioridade = db.tblPrioridade.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                    ViewBag.listaPrioridade = listaPrioridade;

                    var listaRede = db.tblRede.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                   
                    ViewBag.listaRede = listaRede;

                    var listaRecorrencia = db.tblRecorrencia.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                    ViewBag.listaRecorrencia = listaRecorrencia;

                    var listaCanal = db.tblCanal.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                    ViewBag.listaCanal = listaCanal;

                    var listaRazaoContacto = db.tblRazaoContacto.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                    ViewBag.listaRazaoContacto = listaRazaoContacto;

                    lista = Campanha_Manager.GetProductRootList();
                    Session["ListaProduto"] = lista;
                    var listaProduto= lista.Where(a => a.ProductLevel == 0).ToList();
                    ViewBag.listaProduto = listaProduto;
                    ViewBag.listaCampanha = Campanha_Manager.GetCampanhaList(con); ;

                }

                catch (Exception erro)
                {
                    LogInicializer.logger.Info(DateTime.Now + " -CampanhaController - Create)- ", erro);
                    throw erro;
                }
                
            }
            return View();
        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        [HttpPost]
        public JsonResult SetProdutoStatus(int pagina, int estado,int ID)
        {
            bool result = false;
            string mensagem = "";
            string customMsg = "";
            try
            {
                if ((estado == 0 || estado == 1) && ID > 0 )
                {
                    result = Campanha_Manager.UpdateProdutoStatus(estado: estado,ID: ID,con: con);
                    customMsg = estado == 1 ? "Produto Activado com Sucesso!" : "Produto Desactivado com Sucesso!";
                    mensagem = result == false ? "" : customMsg;
                }

                return Json(new { status = result, msg = mensagem }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception erro)
            {
                LogInicializer.logger.Info(DateTime.Now + " -CampanhaController- SetProdutoStatus(ID=" + ID + "))- ", erro);
                throw erro;
            }
        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        [HttpPost]
        public JsonResult SetCampanhaStatus(int pagina, int estado, int campanhaID)
        {
            bool result = false;
            string mensagem = "";
            string customMsg = "";
            try
            {
                if ((estado==0 || estado ==1) && campanhaID >0)
                {
                    result = Campanha_Manager.UpdateCampanhaStatus(estado: estado ,campanhaID: campanhaID ,con:con);
                    customMsg = estado == 1 ? "Campanha activada com Sucesso!" : "Campanha desactivada com Sucesso!";
                    mensagem = result == false ? "" : customMsg;
                }

                return Json(new { status = result, msg = mensagem }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception erro)
            {
                LogInicializer.logger.Info(DateTime.Now + " -CampanhaController - SetCampanhaStatus(campanhaID=" + campanhaID + "))- ", erro);
                throw erro;
            }

        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        [HttpPost]
        public JsonResult RemoveProduct(int ID)
        {
            bool result = false;
            string mensagem = "";
            try
            {
                if (ID > 0)
                {
                    result = Campanha_Manager.DeleteProdutoCampanha(ID: ID, con: con);
                    mensagem = result == false ? "" : "Removido com Sucesso!";
                }

                return Json(new { status = result, msg = mensagem }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception erro)
            {
                LogInicializer.logger.Info(DateTime.Now + " -CampanhaController - RemoveProduct(ID=" + ID + "))- ", erro);
                throw erro;
            }

        }

        public JsonResult Manutencao(Campanha campanha)
        {
            try
            {
                bool status = false;
                Int32 resultado = 0;
                string mensagem = "";
             
                if (campanha != null)
                {
                   resultado = Campanha_Manager.UpdateCampanha(campanha, con, Session["UserID"].ToString());
                       

                        if (resultado > 0)
                        {
                            status = true;
                            Session["CampanhaID"] = resultado;
                            mensagem = "Actualizado com Sucesso!";
                        }
                
                    
                }

                return Json(new { status = status, IDcampanha = campanha.CampanhaID, msg = mensagem }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception erro)
            {
                LogInicializer.logger.Info(DateTime.Now + " -CampanhaController - Manutencao(campanhaID=" + campanha.CampanhaID + "))- ", erro);

GCC/Controllers/RecorrenciaController.cs
using GCC.Class;
using GCC.Managers;
using GCC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GCC.Controllers
{
    public class RecorrenciaController : Controller
    {
        // GET: Recorrencia
        string con = ConnectionDB.GetDBConnectionString;
        public ActionResult Index()
        {
            using (GCCEntities db = new GCCEntities(con))
            {
                try
                {
                    var listaRecorrencia = db.tblRecorrencia.Where(a => a.Estado == true).OrderBy(a => a.ID).ToList();
                    ViewBag.listaRecorrencia = listaRecorrencia;
                }

                catch (Exception erro)
                {
                    LogInicializer.logger.Info(DateTime.Now + " -RecorrenciaController - Index)- ", erro);
                    throw erro;
                }
                return View();
            }
        }
        public ActionResult Details(int id)
        {
            vw_Log_Recorrencia recorencia = new vw_Log_Recorrencia();
            using (GCCEntities db = new GCCEntities(con))
            {
                try
                {
                    recorencia = db.vw_Log_Recorrencia.SingleOrDefault(a=>a.ID==id);
                }

                catch (Exception erro)
                {
                    LogInicializer.logger.Info(DateTime.Now + " -RecorrenciaController - Details)- ", erro);
                    throw erro;
                }

            }
            //return View();
            return PartialView(recorencia);
        }
        public ActionResult RecorrenciaPorExecutar()
        {
            var lista = Recorrencia_Manager.GetRecorrenciaPorExecutar(con:con);
            return View("PorExecutar", lista);
        }
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        [HttpPost]
        public JsonResult GetRecorrenciaChart(int Periodo, int Recorrencia = 100)
        {
            bool status = false;
            string mensagem = "";
            List<RecorrenciaChart> list = new List<RecorrenciaChart>();
            try
            {
                list = Recorrencia_Manager.GetCampanhaListChart(con, Periodo: Periodo, Recorrencia: Recorrencia);
                status = true;
                //status = list.Count > 0 ? true : false;
                
            }
            catch (Exception erro)
            {
                LogInicializer.logger.Info(DateTime.Now + " -RecorrenciaController - GetRecorrenciaChart)- ", erro);
                throw erro;
            }
            //return new JsonResult { Data = lista, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            return Json(new { status = status, data = list,msg=mensagem }, JsonRequestBehavior.AllowGet);

        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        [HttpPost]
        public JsonResult GetRecorrencias(int pagina,int Periodo,int Recorrencia=100, int? Estado = 100)
        {
            bool status = false;
            List<vw_Log_Recorrencia> list = new List<vw_Log_Recorrencia>();
            List<vw_Log_Recorrencia> lista = new List<vw_Log_Recorrencia>();
            Pagination page = new Pagination();
            try
            {
                list = Recorrencia_Manager.GetCampanhaList(con, Periodo: Periodo, Recorrencia: Recorrencia, Estado: Estado);
                status = list.Count > 0 ? true : false;
                page.PageIndex = pagina;
                page.PageSize = 5;
                page.RecordCount = list.Count;
                int startIndex = (pagina - 1) * page.PageSize;
                lista = list
                                .OrderByDescending(a => a.ID)
                                .Skip(startIndex)
                                .Take(page.PageSize).ToList();
            }
            catch (Exception erro)
            {
                LogInicializer.logger.Info(DateTime.Now + " -RecorrenciaController - GetRecorrencia)- ", erro);
                throw erro;
            }
            //return new JsonResult { Data = lista, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            return Json(new { status = status, data = lista, pagina = page }, JsonRequestBehavior.AllowGet);


        }
    }
}

GCC/Views/Shared/_Header.cshtml
<link rel="icon" href="~/Images/Millennium.ico" type="image/x-icon" />
<title>GESTOR DE CAMPANHAS COMERCIAIS</title>
<link href="~/Content/css/material-icons.css" rel="stylesheet" type="text/css" />
<link href="~/Content/plugins/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css" />
<link href="~/Content/plugins/node-waves/waves.css" rel="stylesheet" type="text/css" />
<link href="~/Content/plugins/animate-css/animate.css" rel="stylesheet" type="text/css" />
<link href="~/Content/plugins/material-design-preloader/md-preloader.css" rel="stylesheet" type="text/css" />
<link href="~/Content/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet" />
<link href="~/Content/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet" />
<link href="~/Content/plugins/waitme/waitMe.css" rel="stylesheet" type="text/css" />
<link href="~/Content/plugins/sweetalert/sweetalert.css" rel="stylesheet" />
<!-- Latest compiled and minified CSS -->
<link href="~/Content/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" type="text/css" />
<link href="~/Content/css/style.css" rel="stylesheet" type="text/css" />
<link href="~/Content/css/themes/theme-pink.css" rel="stylesheet" type="text/css" />
@*<link href="~/Content/css/themes/all-themes.css" rel="stylesheet" type="text/css"/>*@
@*<link href="~/Content/sweetalert2.min.css" rel="stylesheet" />*@
<script src="~/Content/plugins/jquery/jquery.min.js" type="text/javascript"></script>
<script src="~/Content/plugins/bootstrap/js/bootstrap.js" type="text/javascript"></script>
<script src="~/Scripts/toastr.min.js"></script>
<link href="~/Content/toastr.min.css" rel="stylesheet" />
<script src="~/Content/plugins/jquery-datatable/jquery.dataTables.js"></script>
<script src="~/Content/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>

<script src="~/Scripts/js/pages/tables/jquery-datatable.js"></script>



@*<script src="~/Scripts/sweetalert2.all.min.js"></script>
    <script src="~/Scripts/core.js"></script>*@
<script type="text/javascript">
        $(document).ready(function () {
            $('.selectpicker').selectpicker('refresh');
        });
</script>
<style  type="text/css">
    .titulos{
        color:black ;
        font: bold 
           
    }
    /*.Pager span {
            text-align: center;
            color: #333;
            display: inline-block;
            width: 20px;
            background-color: #B8DBFD;
            margin-right: 3px;
            line-height: 150%;
            border: 1px solid #B8DBFD;
        }

.Pager a {
    text-align: center;
    display: inline-block;
    width: 20px;
    background-color: #ccc;
    color: #333;
    border: 1px solid #ccc;
    margin-right: 3px;
    line-height: 150%;
    text-decoration: none;
}*/
</style>

GCC/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
   
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    @Html.Partial("_Header")
    @RenderSection("metatags", false)
</head>
<body class="theme-pink">
   @* class="theme-red"*@ 
    @Html.Partial("_TopBar")

    @Html.Partial("_SideBar")

    <section class="content">
        <div class="container-fluid">
            @RenderBody()
             
        </div>
    </section> 


    <script src="~/Content/plugins/bootstrap-select/js/bootstrap-select.js" type="text/javascript"></script>
    <script src="~/Content/plugins/jquery-slimscroll/jquery.slimscroll.js" type="text/javascript"></script>
    @*<script src="~/Content/plugins/node-waves/waves.js" type="text/javascript"></script>*@
    <script src="~/Scripts/waves.js"></script>
    <script src="~/Content/plugins/sweetalert/sweetalert.min.js"></script>
    <script src="~/Content/plugins/jquery-countto/jquery.countTo.js" type="text/javascript"></script>
    <script src="~/Content/plugins/jquery-validation/jquery.validate.js" type="text/javascript"></script>
    <script src="~/Content/plugins/jquery-steps/jquery.steps.js" type="text/javascript"></script>
    <script src="~/Content/plugins/bootstrap-notify/bootstrap-notify.js" type="text/javascript"></script>
    <script src="~/Content/plugins/autosize/autosize.js" type="text/javascript"></script>
    <script src="~/Content/plugins/momentjs/moment.js" type="text/javascript"></script>
    <script src="~/Scripts/moment-with-locales.js"></script>
    <script src="~/Content/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js" type="text/javascript"></script>
    <script src="~/Scripts/js/pages/cards/colored.js" type="text/javascript"></script>
    <script src="~/Scripts/js/admin.js" type="text/javascript"></script>
    <script src="~/Scripts/js/pages/forms/basic-form-elements.js"></script>
    <script src="~/Scripts/js/pages/forms/form-validation.js"></script>
    <script src="~/Scripts/js/pages/ui/tooltips-popovers.js" type="text/javascript"></script>
  
    <script text="text/javascript">
       
        $(document).ready(function () {
            if (checkSession() == false) {
                swal("Atenção!", "A SESSÃO EXPIROU P.F SAIA E VOLTE A ENTRAR NO PROGRAMA", "info");
            }
            var str = location.href.toLowerCase();
           
           $(".theme-pink .sidebar .menu .list .ml-menu li a").each(function () {
                if (str.indexOf(this.href.toLowerCase()) > -1) {
                    var t = $(this);
                    
                    $('.theme-pink .sidebar .menu .list li.active').removeClass('active');
                    t.closest('li').addClass('active');
                    t.closest('.dropdown').addClass("active");
                }
           });
           $(".sidebar .menu .list .ml-menu li .ml-menu li a").each(function () {
               if (str.indexOf(this.href.toLowerCase()) > -1) {
                   var t = $(this);
                  
                   $('.theme-pink .sidebar .menu .list li.active').removeClass('active');
                   t.closest('li').addClass('active');
                   t.closest('.dropdown').addClass("active");
                   t.closest('.dropdown1').addClass("active");
               }
           });

           function checkSession()
           {
               var result;
               $.ajax({

                   type: 'POST',
                   dataType: 'json',
                   contentType: 'application/json',
                   url: "@Url.Action("checkSession", "Home")",
                   data: '{}',
               success: function (data) {
               
                   result = data.sessionValue;
                
               },
               error: function (XMLHttpRequest, textStatus, errorThrown) {
                   var titleText = textFromHTMLString(XMLHttpRequest.responseText, 'title');
                   swal("Erro...", titleText, "error");

               }
           });
           return result;
           }
            function textFromHTMLString(html, target) {
                if (!html || !target) {
                    return false;
                }
                else {
                    var fragment = document.createDocumentFragment(),
                        container = document.createElement('div');
                    container.innerHTML = html;
                    fragment.appendChild(container);
                    var targets = fragment.firstChild.getElementsByTagName(target),
                        result = [];

                    for (var i = 0, len = targets.length; i < len; i++) {
                        result.push(targets[i].textContent || targets[i].innerText);
                    }
                    return result;
                }
            }
        })
       
       
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>
   <!-- Large Size -->
@*<div class="modal fade" id="CampanhaModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

            <div class="modal-body" id="CampanhaModalBody">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link waves-effect">SAVE CHANGES</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
</div>*@

GCC/Views/Shared/_Sidebar.cshtml
@{
    string serverName = Server.MachineName;
}
<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->

        <div class="user-info">
            <div class="image" style="margin-left :70px!important">
                @if (Session["UserImage"] != null)
                { <img src=@Session["UserImage"] width="70" height="70" alt="User" />}
                else
                {
                    
                    <img src="~/Images/images.png" width="70" height="70" alt="User" />
                }

                
            </div>
            @if (@Session["UserID"] != null)
            {
            <div class="info-container">
                <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   @Session["XnucName"]
                </div>
                <div class="email">
                    @Session["UnidadeOrganicaDescricao"]
                </div>
            </div>
            }
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">MENU</li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")">
                        <i class="material-icons">home</i>
                        <span>Pagina Inicial</span>
                    </a>
                </li>
               @{
                   List<string> roles = new List<string>();
                   if (@Session["UserRoles"] != null)
                   {
                       roles = (List<string>)Session["UserRoles"];
                   }

                   if (User.IsInRole("GCC_REGISTO_CAMPANHA") || (roles != null && roles.Contains("GCC_REGISTO_CAMPANHA")))
                   {
                <li class="dropdown">
                    <a href="javascript:void(0);" class="menu-toggle">
                        @*<i class="material-icons">volume_up</i>*@
                        <i class="material-icons">notifications_active</i>
                        <span>Campanha</span>
                    </a>
                    <ul class="ml-menu">
                        <li>
                            <a href="@Url.Action("Create", "Campanha")">
                                <span>Registo da Campanha</span></a>
                        </li>

                        <li>
                            <a href="@Url.Action("Parametrizacao", "Home")">
                                <span>Parametrização Geral</span>
                            </a>
                           
                        </li>
                        @*<li class="dropdown1">
                            <a href="javascript:void(0);" class="menu-toggle">
                                <span>Recorrência</span>
                            </a>
                            <ul class="ml-menu">
                                <li>
                                    <a href="@Url.Action("Index", "Recorrencia")"><span>Log de Recorrências</span></a>
                                </li>
                                <li>
                                    <a href="@Url.Action("RecorrenciaPorExecutar", "Recorrencia")"><span>Recorrências por Executar</span></a>
                                </li>
                                
                            </ul>
                        </li>*@
                    </ul>
                </li>
                   }
            }
                <li class="dropdown">
                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">cached</i>
                        <span>Recorrência</span>
                    </a>
                    <ul class="ml-menu">
                        <li>
                            <a href="@Url.Action("Index", "Recorrencia")"><span>Log de Recorrências</span></a>
                        </li>
                        <li>
                            <a href="@Url.Action("RecorrenciaPorExecutar", "Recorrencia")"><span>Recorrências por Executar</span></a>
                        </li>

                    </ul>
                </li>
                <li data-toggle="tooltip" data-placement="right" title="" data-original-title="Ver Manual do Utilizador">
                    
                    <a href="@Url.Action("DownloadUserManual", "Home")" class="waves-effect waves-block">
                        <i class="material-icons">help</i>
                        <span>Ajuda</span>
                    </a>
                </li>
                <li data-toggle="tooltip" data-placement="right" title="" data-original-title="Sair da aplicação">
                    <a href="@Url.Action("Logout", "Home")" class="waves-effect waves-block">
                        <i class="material-icons">input</i>
                        <span>Sair</span>
                    </a>
                </li>

            </ul>
        </div>
        <!-- #Menu -->
        <!-- Footer -->
        <div class="legal">
            <div class="version">
                <label ID="lblServidor" style="color:#B32251;margin-left: 25px">@serverName</label>
            </div>
            <div class="copyright" style="color:#B32251">
                &copy;
                <script>
                        var CurrentYear = new Date().getFullYear()
                        document.write(CurrentYear)
                </script>

                <a href="javascript:void(0);">
                    <label ID="lblServidor" Text="Label">MillenniumBim</label>
                </a>.
            </div>
            
        </div>
        <!-- #Footer -->
    </aside>
    <!-- #END# Left Sidebar -->
   
</section>

GCC/Views/Shared/_TopBar.cshtml
 <!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="md-preloader pl-size-md">
            <svg viewbox="0 0 75 75">
                <circle cx="37.5" cy="37.5" r="33.5" class="pl-red" stroke-width="4" />
            </svg>
        </div>
        <p>Aguarde por Favor...</p>
    </div>
</div>
<!-- #END# Page Loader -->
<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- #END# Overlay For Sidebars -->
<!-- Search Bar -->

<!-- #END# Search Bar -->
<!-- Top Bar -->

<nav class="navbar" style="background-color :#b32251!important ">
    <div class="container-fluid">

        <div class="navbar-header">


            <a class="bars" style="cursor: pointer; display: block;"></a>

            <img src="/GCC/Images/Millennium.png">


            <a class="navbar-brand">GESTOR DE CAMPANHAS</a>

        </div>

    </div>
</nav>
<!-- #Top Bar -->